#ifndef COMMON_NSH_CONSTANTS_H_
#define COMMON_NSH_CONSTANTS_H_

#define VXLAN_GPE_UDP_PORT 4790
#define VXLAN_NEXT_PROTOCOL_NSH 0x04
#define NSH_NEXT_PROTOCOL_IPv4 1
#define NSH_NEXT_PROTOCOL_IPv6 2
#define NSH_NEXT_PROTOCOL_ETHERNET 3
#define VXLAN_HEADER_SIZE 8
#define NSH_BASE_HEADER_LEN 4
#define NSH_SERVICE_PATH_HEADER_LEN 4
#define NSH_VAR_LEN_CTX_BASE_HEADR_LEN 4

#define MATCH_REPORT_SIZE 5
#define MATCH_REPORT_RANGE_SIZE 7

#define IP_HEADER_SIZE 20
#define UDP_HEADER_SIZE 8

#endif /* COMMON_NSH_CONSTANTS_H_ */
