#ifndef COMMON_NSH_CONSTANTS_H_
#define COMMON_NSH_CONSTANTS_H_

#define VXLAN_GPE_UDP_PORT 4790
#define VXLAN_NEXT_PROTOCOL_NSH 0x04
#define NSH_NEXT_PROTOCOL_IPv4 1
#define NSH_NEXT_PROTOCOL_IPv6 2
#define NSH_NEXT_PROTOCOL_ETHERNET 3

#define IP_HEADER_SIZE 20
#define UDP_HEADER_SIZE 8

#endif /* COMMON_NSH_CONSTANTS_H_ */
